spring:
  profiles:
    active: dev
  application:
    name: eureka-provider
server:
  port: 82

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint: #配置可以远程关闭
    shutdown:
      enabled: true

---
spring:
  profiles: prod
server:
  port: 81

eureka:
  client:
    service-url:
      # 设置服务注册中心的URL，用于client和server端交流
      # #此节点应向其他节点发起请求，填写别的节点的ip
      defaultZone: http://@60.188.58.167:7001/eureka/
  instance:
    hostname: 60.188.58.167
    ip-address: 60.188.58.167
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}

---
spring:
  profiles: dev
server:
  port: 82
eureka:
  client:
    service-url:
      # 设置服务注册中心的URL，用于client和server端交流
      defaultZone: http://eureka1:7001/eureka/, http://eureka2:7002/eureka/, http://eureka3:7003/eureka/
  instance:
    hostname: six66 # 不关键，如果ip-address有显示标注，则hostname就是ip-address，否则会显示这里配置的hostname,如果去掉则显示真正的主机名
    ip-address: whisper
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}