
spring:
  application:
    name: zuul-server

server:
  port: 80

eureka:
  client:
    service-url:
      ## http://localhost/eureka-provider/get \u76F4\u63A5\u8BBF\u95EE\u8FD9\u4E2A\u662F\u53EF\u4EE5\u6253\u5230provider\u4E0A\u53BB\u7684
      defaultZone: http://eureka1:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      enabled: true # default true
    routes:
      enabled: true # default true

provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

zuul:
  routes:
    provider: /xxoo/**
    