spring:
  profiles:
    active: dev
  application:
    name: eureka-consumer
server:
  port: 90

# 自定义负载策略，优先级大于启动类中的Bean
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#关闭eureka，不走ribbon负载，只用80的负载
#ribbon:
#  eureka:
#    enabled: false # 关闭负载
#  listOfServers: localhost:80

---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      # 设置服务注册中心的URL，用于client和server端交流
      defaultZone: http://eureka1.com:7001/eureka/
  instance:
    hostname: sb
    ip-address: 192.168.37.131
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}


---
spring:
  profiles: prod
eureka:
  client:
    service-url:
      # 设置服务注册中心的URL，用于client和server端交流
      defaultZone: http://60.188.58.167:7001/eureka/

