spring:
  application:
    name: user-provider
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      rate: 1

server:
  port: 81
eureka:
  client:
    service-url:
      # 设置服务注册中心的URL，用于client和server端交流
      defaultZone: http://eureka1.com:7001/eureka/





